### PR TITLE
mixin: increment mixer version when necessary

### LINKED ISSUE #347: mixin: the version number is not incremented on subsequent builds
After first mixin, migrate, bundle install, and then creation of a new mixin, the version number didn't increment as expected.  Here's an example:

clear@clear-os ~ $ sudo -E mixin package add helloworld --bundle helloworld-bundle
Initializing mix version 23000000 from upstream version 23000
Bundle "os-core" already in mix; skipping
Adding bundle "helloworld-bundle" from local bundles
Added helloworld package to helloworld-bundle bundle.
clear@clear-os ~ $ sudo -E mixin package add helloworld --bundle helloworld-bundle^C
clear@clear-os ~ $ sudo -E mixin build
Directory walk started
Directory walk done - 0 packages
Temporary output repo path: ./.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
Generating certificate for signature validation...
Building bundles...
=> BUILD BUNDLES
Creating bundles for version 23000000 based on Clear Linux 23000
Preparing new /usr/share/mix/update/image/23000000
  and dnf config: /usr/share/mix/.yum-mix.conf
Packager command-line: dnf --config=/usr/share/mix/.yum-mix.conf -y --releasever=23000
Resolving packages using 2 workers
processing helloworld-bundle
processing os-core
... done with helloworld-bundle
... done with os-core
Resolving files using 2 workers
processing helloworld-bundle
processing os-core
Bundle os-core	3105 files
Bundle helloworld-bundle	263 files
Cleaning DNF cache before full install
Installing all bundles to full chroot
[1/2] helloworld-bundle
[2/2] os-core
... building special os-core content
... Adding swupd default values to os-core bundle

TIMINGS
  BUILD BUNDLES 7.994s
TOTAL: 7.994s
=> CREATE MANIFESTS
[1/3] helloworld-bundle
[2/3] os-core
[3/3] full
MoM version 23000000
- helloworld-bundle    23000000
- os-core              23000000
- os-core-update-index 23000000
Signing manifest.
Compressing Manifest.MoM
Compressing bundle manifests
  helloworld-bundle
  os-core
  os-core-update-index
  full

=> CREATE FULLFILES
Using 2 workers
- Already created: 0
- Not compressed:  0
- Compressed
  - external-bzip2       99
  - gzip                 316
  - external-xz          924
  - external-gzip        1033
Total fullfiles: 2372

=> CREATE ZERO PACKS
Creating zero pack for helloworld-bundle to version 23000000
  Fullfiles in pack: 5
  Deltas in pack: 0
Creating zero pack for os-core to version 23000000
  Fullfiles in pack: 2364
  Deltas in pack: 0
Creating zero pack for os-core-update-index to version 23000000
  Fullfiles in pack: 5
  Deltas in pack: 0
Saving the upstream URL: https://download.clearlinux.org
Saving the upstream version: 23000
Setting latest version to 23000000

TIMINGS
  CREATE MANIFESTS  922ms
  CREATE FULLFILES  18.537s
  CREATE ZERO PACKS 11.684s
TOTAL: 31.144s
* Verified upstream Manifest.MoM
Successfully built mix content
clear@clear-os ~ $ sudo -E swupd update --migrate
Attempting to migrate to your mix content...

Update started.
Preparing to update from 23000 to 23000000
Downloading packs...
	...100%

Statistics for going from version 23000 to version 23000000:

    changed bundles   : 1
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 3107
    new files         : 0
    deleted files     : 0

Starting download of remaining update content. This may take a while...

Finishing download of update content...
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
Update took 5.3 seconds
Update successful. System updated from version 23000 to version 23000000
clear@clear-os ~ $ sudo -E swupd check-update
Current OS version: 23000000
There are no updates available
clear@clear-os ~ $ sudo -E swupd bundle-add helloworld-bundle
Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.
Bundle(s) installation done.
clear@clear-os ~ $ helloworld
Hello world
clear@clear-os ~ $ sudo -E mixin package add joe --bundle joe-bundle
Initializing mix version 23000000 from upstream version 23000
Bundle "os-core" already in mix; skipping
Adding bundle "joe-bundle" from local bundles
Added joe package to joe-bundle bundle.
clear@clear-os ~ $ sudo -E mixin build
Directory walk started
Directory walk done - 0 packages
Temporary output repo path: ./.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
Building bundles...
=> BUILD BUNDLES
Wiping away previous version 23000000...
Creating bundles for version 23000000 based on Clear Linux 23000
Preparing new /usr/share/mix/update/image/23000000
  and dnf config: /usr/share/mix/.yum-mix.conf
Packager command-line: dnf --config=/usr/share/mix/.yum-mix.conf -y --releasever=23000
Resolving packages using 2 workers
processing os-core
processing helloworld-bundle
... done with helloworld-bundle
processing joe-bundle
... done with joe-bundle
... done with os-core
Resolving files using 2 workers
processing os-core
processing helloworld-bundle
Bundle os-core	3105 files
processing joe-bundle
Bundle helloworld-bundle	263 files
Bundle joe-bundle	768 files
Cleaning DNF cache before full install
Installing all bundles to full chroot
[1/3] os-core
... building special os-core content
... Adding swupd default values to os-core bundle
[2/3] helloworld-bundle
[3/3] joe-bundle

TIMINGS
  BUILD BUNDLES 17.241s
TOTAL: 17.241s
=> CREATE MANIFESTS
[1/4] os-core
[2/4] helloworld-bundle
[3/4] joe-bundle
[4/4] full
MoM version 23000000
- helloworld-bundle    23000000
- joe-bundle           23000000
- os-core              23000000
- os-core-update-index 23000000
Signing manifest.
Compressing Manifest.MoM
Compressing bundle manifests
  os-core
  helloworld-bundle
  joe-bundle
  os-core-update-index
  full

=> CREATE FULLFILES
Using 2 workers
- Already created: 0
- Not compressed:  0
- Compressed
  - external-gzip        1096
  - external-bzip2       118
  - gzip                 317
  - external-xz          959
Total fullfiles: 2490

=> CREATE ZERO PACKS
Creating zero pack for helloworld-bundle to version 23000000
  Fullfiles in pack: 5
  Deltas in pack: 0
Creating zero pack for joe-bundle to version 23000000
  Fullfiles in pack: 119
  Deltas in pack: 0
Creating zero pack for os-core to version 23000000
  Fullfiles in pack: 2364
  Deltas in pack: 0
Creating zero pack for os-core-update-index to version 23000000
  Fullfiles in pack: 6
  Deltas in pack: 0
Saving the upstream URL: https://download.clearlinux.org
Saving the upstream version: 23000
Setting latest version to 23000000

TIMINGS
  CREATE MANIFESTS  990ms
  CREATE FULLFILES  19.372s
  CREATE ZERO PACKS 12.274s
TOTAL: 32.637s
* Verified upstream Manifest.MoM
ERROR: open /usr/share/mix/update/www/23000000/Manifest.MoM: no such file or directory

### PR DESCRIPTION
**Pull request by matthewrsj**
Fixes #347

Signed-off-by: Matthew Johnson <matthew.johnson@intel.com>

### CODE REVIEW

File: mixin/build.go [hunk 1]
```diff
@@ -104,6 +107,20 @@ func mergeMoMs(mixWS string, mixVer, lastVer int) error {
 	return upstreamMoM.WriteManifestFile("Manifest.MoM")
 }
 
+func incrementMixVerIfNeeded(mixVer int, mixFlagFile string) int {
+	out, err := ioutil.ReadFile(mixFlagFile)
+	if err != nil {
+		return mixVer
+	}
+
+	ver, err := strconv.ParseInt(strings.TrimSpace(string(out)), 10, 32)
```
Comment (icarus-sparry) [inline mixin/build.go]: I would tend to use strconv.Atoi(strings.TrimSpace(out)) if I didn't need to be able to specify the base.

If you are sticking with ParseInt then specify the bit size as 0, so the conversion returns an "int" rather than an "int32", which would also remove the need for a cast to int.

Just possibly consider strconv.ParseUInt?

Comment (matthewrsj) [reply mixin/build.go]: Ah, `Atoi` is a much better choice, thank you.

Comment (matthewrsj) [reply mixin/build.go]: done
