### PR TITLE
Fix rpm filename convention

### LINKED ISSUE #648: [BBT][mixer]fail to create minimal mix
In build 31670, we have a regression for mixer bundle, it fail when try ti create a minimal mix.

rpm2archive cmd fails with Chrome RPM

This is the error
```
# Packager command-line: dnf --config=/tmp/tmp.jwm9geWJKe/.yum-mix.conf -y --releasever=31660
# Resolving packages using 4 workers
# processing findutils
# processing os-core-plus
# processing bootloader
# processing os-core
# ... done with os-core
# processing libstdcpp
# ... done with bootloader
# processing p11-kit
# ... done with p11-kit
# processing kernel-kvm
# ... done with kernel-kvm
# processing syslinux
# ... done with syslinux
# processing qemu-guest-additions
# ... done with qemu-guest-additions
# processing os-core-update
# ... done with os-core-update
# processing os-core-webproxy
# ... done with os-core-webproxy
# processing libglib
# ... done with os-core-plus
# processing chrome
# ... done with libstdcpp
# ... done with libglib
# ... done with findutils
# ... done with chrome
# Resolving files using 4 workers
# processing findutils
# processing os-core-plus
# processing bootloader
# processing os-core
# Bundle os-core-plus	2219 files
# processing libstdcpp
# Bundle os-core	2283 files
# Bundle libstdcpp	299 files
# processing kernel-kvm
# processing p11-kit
# Bundle p11-kit	1366 files
# processing syslinux
# Bundle syslinux	533 files
# processing qemu-guest-additions
# Bundle qemu-guest-additions	460 files
# processing os-core-update
# Bundle os-core-update	5103 files
# processing os-core-webproxy
# Bundle os-core-webproxy	2764 files
# processing libglib
# Bundle libglib	411 files
# processing chrome
# Bundle bootloader	566 files
# Bundle kernel-kvm	2012 files
# Bundle findutils	476 files
# Bundle chrome	6089 files
# Cleaning DNF cache before full install
# Installing all bundles to full chroot
# [1/13] findutils
# [2/13] bootloader
# [3/13] os-core
# ... building special os-core content
# [4/13] os-core-plus
# [5/13] libstdcpp
# [6/13] p11-kit
# [7/13] kernel-kvm
# [8/13] syslinux
# [9/13] qemu-guest-additions
# [10/13] os-core-update
# ... Adding swupd default values to os-core-update bundle
# [11/13] os-core-webproxy
# [12/13] libglib
# [13/13] chrome
# extraction failed for  gdk-pixbuf-libexec-2.40.0-60.x86_64.rpm
#
# TIMINGS
#   BUILD BUNDLES 0s
# TOTAL: 0s
# 2019/11/19 08:02:39 ERROR: Couldn't build bundles: Error building bundles: rpm2archive cmd failed with exit status 1
# /home/clear/BBT/bundles/mixer
```

You can review the test case in [openBBT](https://github.com/clearlinux/openBBT/blob/master/bundles/mixer/bat-mixer.t)

### PR DESCRIPTION
**Pull request by ashleshaAtrey**
Fix rpm filename convention

mixer can now support any format of rpm Name. It uses dnf repoquery to fetch the rpm name.
fixes #648

Signed-off-by: Ashlesha Atrey <ashlesha.atrey@intel.com>

### CODE REVIEW

File: builder/bundles.go [hunk 1]
```diff
@@ -346,7 +352,18 @@ func resolvePackages(numWorkers int, set bundleSet, packagerCmd []string, emptyD
 			for _, pkgs := range fullRpm {
 				// Add packages to bundle's AllPackages
 				for _, pkg := range pkgs {
-					name := pkg.name + "-" + pkg.version + "." + pkg.arch + ".rpm"
+					var name string
+					name = pkg.name + "-" + pkg.version + "." + pkg.arch + ".rpm"
+					if pkg.repo == "local" {
+						if _, err := os.Stat(filepath.Join(localPath, name)); os.IsNotExist(err) {
```
Comment (rchiossi) [inline builder/bundles.go]: Can we have this block plus the query string above on a dedicated function? It will make it easier to read the code.

File: builder/bundles.go [hunk 2]
```diff
@@ -346,7 +352,18 @@ func resolvePackages(numWorkers int, set bundleSet, packagerCmd []string, emptyD
 			for _, pkgs := range fullRpm {
 				// Add packages to bundle's AllPackages
 				for _, pkg := range pkgs {
-					name := pkg.name + "-" + pkg.version + "." + pkg.arch + ".rpm"
+					var name string
```
Comment (rchiossi) [inline builder/bundles.go]: Just use `:=` on the line below

**Comment by ashleshaAtrey** [comment]
@rchiossi No noticeable impact in performance when all packages are local and are properly named. But if the number of external rpms will increase to a significant amount, we might see an impact on performance.

File: builder/bundles.go [hunk 3]
```diff
@@ -347,6 +365,14 @@ func resolvePackages(numWorkers int, set bundleSet, packagerCmd []string, emptyD
 				// Add packages to bundle's AllPackages
 				for _, pkg := range pkgs {
 					name := pkg.name + "-" + pkg.version + "." + pkg.arch + ".rpm"
```
Comment (reaganlo) [inline builder/bundles.go]: Can you please rename the variable `name` to `rpmName`

File: builder/bundles.go [hunk 4]
```diff
@@ -347,6 +365,14 @@ func resolvePackages(numWorkers int, set bundleSet, packagerCmd []string, emptyD
...
+					if pkg.repo == "local" {
+						if _, err := os.Stat(filepath.Join(localPath, name)); os.IsNotExist(err) {
+							name = queryRpmName(packagerCmd, pkg.name)
+							if name == "" {
```
Comment (reaganlo) [inline builder/bundles.go]: I don't think we should check if its empty and revert back the hard-coded name. 
Since the first dnf query has already found the package in the local repo, there should not be a reason why the output of queryRpmName() is empty. If it happens to be empty for some weird reason, let it error out later in the code.

File: builder/bundles.go [hunk 5]
```diff
@@ -312,9 +312,27 @@ func repoPkgFromNoopInstall(installOut string) (repoPkgMap, repoRpmMap) {
...
+		"repoquery",
+		"--location",
+		"--repo local",
+	)
+	var name string
+	queryStringRpm = append(queryStringRpm, pkgName)
+	outBuf, _ := helpers.RunCommandOutputEnv(queryStringRpm[0], queryStringRpm[1:], []string{"LC_ALL=en_US.UTF-8"})
+	if outBuf.String() != "" {
+		rpm := strings.Split(outBuf.String(), "\n")
+		_, name = filepath.Split(rpm[0])
```
Comment (reaganlo) [inline builder/bundles.go]: Like what @rchiossi suggested, remove `var name string` and just use `_, name :=` here.

File: builder/bundles.go [hunk 6]
```diff
@@ -312,9 +312,27 @@ func repoPkgFromNoopInstall(installOut string) (repoPkgMap, repoRpmMap) {
 	return repoPkgs, repoRpmMap
 }
 
+func queryRpmName(packageCmd []string, pkgName string) string {
+	queryStringRpm := merge(
+		packageCmd,
+		"repoquery",
+		"--location",
+		"--repo local",
```
Comment (reaganlo) [inline builder/bundles.go]: I don't think this query is returning the rpm file names from JUST the **local** repo. If the package exists in both the `local` and `clear` repo, both the rpm file names are returned.
Can you please confirm this?

Comment (ashleshaAtrey) [reply builder/bundles.go]: fixed it!

**Comment by reaganlo** [comment]
Editing the commit message and merging.
